apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sample-app
  namespace: argocd
spec:
  destination:
    namespace: sample-app
    server: 'https://kubernetes.default.svc'
  source:
    path: app-sample
    repoURL: 'https://github.com/mahdieuch/kube-argocd-project.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true

