apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: voteapp
  namespace: argocd
spec:
  destination:
    namespace: app-vote
    server: 'https://kubernetes.default.svc'
  source:
    path: app-vote
    repoURL: 'https://github.com/mahdieuch/kube-argocd-project.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

